name: 'List Members'
description: "GitHub Action to generate an organization's members list as JSON"
author: RITct

inputs:
  org-name:  # id of input
    description: 'Organization Name'
    required: true
  file-path: #id of input
    description: 'Json file'
    required: false
    default: "members.json"
  commit-user-name:
    description: 'Commit Username'
    required: false
    default: "list-member-action"
  commit-user-email:
    description: 'Commit Email'
    required: false
    default: "listaction@noreply.com"
  commit-msg:
    description: 'Commit Message'
    required: false
    default: "changed members file"
outputs:
  message:
    description: "generated members json"
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'user'
  color: 'blue'